version: "3"
services:
  publish:
    build: .
    tty: true
    image: improvado_async_hvac
    volumes:
      - .:/usr/src/app/
      - .pypirc:/root/.pypirc
    command: ./publish.sh
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_REGION=${AWS_REGION}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
